finish homework week3
baharehsichani/hyf-homework pull request #7
Opened 2021-11-12 18:35 UTC by baharehsichani

2021-11-13 20:09 UTC, aina21 requested changes
remove unrelated file for week2 from this PR

2021-11-13 20:10 UTC, aina21 requested changes

2021-11-13 20:10 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +  var str=calculateHour.toString()
don't use var. you can use const instead

2021-11-13 20:10 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +  var numarray=str.split('.')
const

2021-11-13 20:10 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +  var a=new Array()
const

2021-11-13 20:11 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +age*=(365*24*60)
const age = (365*24*60);

2021-11-13 20:11 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +let seriesDurations = [
const

2021-11-13 20:11 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +    let dayToMinutes= seriesDurations[i].days*24*60
const

2021-11-13 20:11 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +    let hourToMinutes= seriesDurations[i].hours*60
const

2021-11-13 20:12 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +    let totalMinutes= dayToMinutes+hourToMinutes+seriesDurations[i].minutes
const totalMinutes= (dayToMinutes+hourToMinutes+seriesDurations[i].minutes) * 100;

2021-11-13 20:12 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +    totalMinutes*=100
then you don't need this line

2021-11-13 20:12 UTC, aina21 commented on javascript/javascript1/week3/index1.js
> +    let spendTime=(totalMinutes / age).toFixed(3)
const

2021-11-13 20:15 UTC, aina21 commented on javascript/javascript1/week3/index2.js
> +    let obj={
obj is not a good name, I think note or you can also write like 
```
notes.push({
        content:content,
        id:id
    })
```

2021-11-13 20:16 UTC, aina21 commented on javascript/javascript1/week3/index2.js
> +    let obj={
you can read more about naming here
[https://github.com/chunmeishui/hyf-homework/pull/url](url)

2021-11-13 20:26 UTC, aina21 commented on javascript/javascript1/week3/index2.js
> +        if(id != ""){
id type is the number, and you check here if id is not a empty string, it always true.

2021-11-13 20:27 UTC, aina21 commented on javascript/javascript1/week3/index2.js
> +        return (console.log("Id has to be a number"))
it's better to use return string value  or remove return and just log a string.

2021-11-13 20:31 UTC, aina21 commented on javascript/javascript1/week3/index2.js
> +              return (console.log("This id does not exist"))
I think it's not working if you call getId(2), because you return inside a loop.

2021-11-15 19:19 UTC, baharehsichani commented
Thanks for the feedback

2021-11-15 19:19 UTC, merged